name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Choose your Python version
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install your Python dependencies
        # Replace requirements.txt with your requirements file if you have one
    
    - name: Build
      run: |
        # Add commands to build your Python project
        # For example: python build.py or python setup.py build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./path/to/your/html  # Specify the directory with your HTML content
