name: Python CI

on: [push, pull_request]

jobs:
  run-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python Version
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Dependencies
      uses: actions/cache@v3
      id: cache1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      if: steps.cache1.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt

    - name: Run Python Script
      run: python yt_transcriber_app.py

  run-python-test2:
    needs: [run-python]
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python Version
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.12'
