name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # Adjust as needed
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the correct Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit
      - name: Install Streamlit Component Server
        run: |
          npm install -g @streamlit/component-server
      - name: Build and deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          streamlit run yt_transcriber_app.py --server.port ${{ job.services.nginx.ports[80] }} &  # Run your Streamlit app
          component=`npx streamlit-component-server --main-py-file yt_transcriber_app.py --python-version 3.11 --server.port ${{ job.services.nginx.ports[3001] }}`
          npx streamlit-component-server --main-py-file yt_transcriber_app.py --python-version 3.11 --server.port ${{ job.services.nginx.ports[3001] }}
          npx streamlit-component-server --main-py-file yt_transcriber_app.py --python-version 3.11 --server.port ${{ job.services.nginx.ports[3001] }} --browser.serverAddr "streamlit.component-archiver"
          npx streamlit-component-server --main-py-file yt_transcriber_app.py --python-version 3.11 --server.port ${{ job.services.nginx.ports[3001] }} --browser.serverAddr "streamlit.component-archiver" --build
