# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: windows-latest

#     env:
#       GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.12'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Build application
#       run: |
#         python yt_transcriber_app.py 
#     name: Check if gh-pages branch exists
#       run: |
#         git fetch origin gh-pages || git checkout --orphan gh-pages
#         git push -u origin gh-pages

#     - name: Configure Git user
#       run: |
#         git config --global user.email "you@example.com"
#         git config --global user.name "Your Name"
#     - name: Deploy to GitHub Pages
#       run: |
#         git clone --branch gh-pages https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/shalini-nunavath/Transcriber.git gh-pages
#         git add .
#         git commit -m "Deploy to GitHub Pages"
#         git push origin gh-pages


name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build application
      run: |
        python yt_transcriber_app.py

    - name: Check if gh-pages branch exists
      run: |
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git push -u origin gh-pages

    - name: Configure Git user
      run: |
        git config --global user.email "shalini.nunavath@techoptima.in.com"
        git config --global user.name "shalini-nunavath"

    - name: Deploy to GitHub Pages
      run: |
        git clone --branch gh-pages https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/shalini-nunavath/Transcriber.git gh-pages
        cp -r dist/* gh-pages/
        cd gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
