name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch or any branch you prefer

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12 # Choose your Python version
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install your Python dependencies
    
    - name: Run tests  # Optional: Add a step to run tests if needed
      run: |
        streamlit run yt_transcriber_app.py  # Example command for running tests
    
    - name: Build
      run: |
        # If you have a specific build step, add it here
        # For Streamlit, this might be setting up your app
        # Since Streamlit serves the app rather than generating static files,
        # you might want to skip this step or use it for preparation
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./path/to/your/built/files  # Specify the directory with your built files
    
    - name: Run Streamlit app  # Run Streamlit as a separate step
      run: |
        streamlit run yt_transcriber_app.py
